FROM node:alpine

RUN mkdir -p /opt
WORKDIR /opt

COPY node_modules /opt/node_modules
COPY dist /opt/dist
COPY data/prod/configs /opt/configs
COPY data/prod/assets /opt/assets
COPY data/prod/i18n /opt/i18n
COPY .eslint* package.json yarn.lock /opt/

EXPOSE 80
CMD yarn dist:run

